version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres:latest
    container_name: postgres-quarkus
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus
      - POSTGRES_DB=quarkus
